# Generated by Django 2.0.5 on 2018-06-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prjoect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='keywords',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='prjoect',
            name='taxonomy',
            field=models.ManyToManyField(to='Taxonomy.Taxonomy'),
        ),
    ]
