# Generated by Django 2.0.5 on 2018-06-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taxonomy', '0002_auto_20180619_0903'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keywords',
            new_name='Keyword',
        ),
    ]
