# Generated by Django 2.0.5 on 2018-06-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxonomy', '0005_auto_20180619_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
