# Generated by Django 2.0.5 on 2018-06-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternetData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coderunner',
            name='jobname',
            field=models.CharField(default='testjob', max_length=20),
        ),
    ]
