# Generated by Django 2.0.5 on 2018-06-07 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InternetData', '0002_coderunner_jobname'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquireData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(help_text='Enter comma(,) separated keywords')),
                ('available', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('a', 'API'), ('s', 'Scraper'), ('c', 'Crawler')], max_length=10)),
                ('xpaths', models.TextField(blank=True)),
                ('urls', models.TextField(blank=True)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True)),
                ('coderunner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='InternetData.CodeRunner')),
                ('datastore', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='InternetData.DataStore')),
            ],
            options={
                'verbose_name': 'API',
            },
        ),
        migrations.CreateModel(
            name='LoginMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymus', max_length=30)),
                ('website', models.CharField(max_length=30)),
                ('token_key', models.CharField(help_text='Enter the token or Username here', max_length=100)),
                ('token_secret', models.CharField(blank=True, help_text='Enter the Token Secret or Password here', max_length=100)),
                ('consumer_key', models.CharField(blank=True, max_length=100)),
                ('consumer_secret', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='apidata',
            name='apikey',
        ),
        migrations.RemoveField(
            model_name='apidata',
            name='coderunner',
        ),
        migrations.RemoveField(
            model_name='apidata',
            name='datastore',
        ),
        migrations.DeleteModel(
            name='ApiKey',
        ),
        migrations.RemoveField(
            model_name='crawlerdata',
            name='coderunner',
        ),
        migrations.RemoveField(
            model_name='crawlerdata',
            name='datastore',
        ),
        migrations.RemoveField(
            model_name='scraperdata',
            name='coderunner',
        ),
        migrations.RemoveField(
            model_name='scraperdata',
            name='datastore',
        ),
        migrations.DeleteModel(
            name='APIData',
        ),
        migrations.DeleteModel(
            name='CrawlerData',
        ),
        migrations.DeleteModel(
            name='ScraperData',
        ),
        migrations.AlterUniqueTogether(
            name='loginmeta',
            unique_together={('name', 'token_key')},
        ),
        migrations.AddField(
            model_name='acquiredata',
            name='loginmeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='InternetData.LoginMeta'),
        ),
    ]
