# Generated by Django 2.0.5 on 2018-06-14 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InternetData', '0002_auto_20180614_0640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginmeta',
            options={'verbose_name': 'Data Auth'},
        ),
        migrations.RemoveField(
            model_name='pipelinerunner',
            name='password',
        ),
        migrations.RemoveField(
            model_name='pipelinerunner',
            name='token',
        ),
        migrations.RemoveField(
            model_name='pipelinerunner',
            name='username',
        ),
        migrations.AddField(
            model_name='pipelinerunner',
            name='login',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='InternetData.LoginMeta'),
            preserve_default=False,
        ),
    ]
