# Generated by Django 2.0.5 on 2018-06-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternetData', '0003_auto_20180614_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerunner',
            name='jobname',
            field=models.CharField(default='test', max_length=30),
        ),
    ]
