# Generated by Django 2.0.5 on 2018-06-07 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InternetData', '0004_auto_20180607_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquiredata',
            name='coderunner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InternetData.CodeRunner'),
        ),
        migrations.AlterField(
            model_name='acquiredata',
            name='datastore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InternetData.DataStore'),
        ),
    ]
