# Generated by Django 2.0.5 on 2018-06-15 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InternetData', '0005_auto_20180614_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datajob',
            name='loginmeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='InternetData.LoginMeta'),
        ),
        migrations.AlterField(
            model_name='datajob',
            name='scraper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coderunner', to='InternetData.ScraperRunner'),
        ),
    ]
