# Generated by Django 2.0.5 on 2018-06-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternetData', '0007_auto_20180615_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='datajob',
            name='desc',
            field=models.CharField(default='Please insert 50 Char Description', max_length=50),
        ),
    ]
