# Generated by Django 2.0.5 on 2018-06-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternetData', '0008_datajob_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmeta',
            name='consumer_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='loginmeta',
            name='consumer_secret',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='loginmeta',
            name='token_key',
            field=models.CharField(help_text='Enter the token or Username here', max_length=200),
        ),
        migrations.AlterField(
            model_name='loginmeta',
            name='token_secret',
            field=models.CharField(blank=True, help_text='Enter the Token Secret or Password here', max_length=200),
        ),
    ]
